Updated demo script to watch for changes
Allows quick iteration by automatically watching for file changes and reloading the server. link:https://eradman.com/entrproject[Entr] is required for this to work and will error if not installed with instructions for correcting.

Milestone: minor

diff --git a/bin/demo b/bin/demo
--- a/bin/demo
+++ b/bin/demo
@@ -5,17 +5,23 @@ set -o errexit
 set -o pipefail
 IFS=$'\n\t'
 
-port="${1:-3030}"
+if ! command -v entr > /dev/null; then
+  printf "%s" "ERROR: Entr isn't installed: https://eradman.com/entrproject. "
+  printf "%s\n" "To fix, run: brew install entr."
 
-rm -rf tmp/demo
-mkdir -p tmp/demo
+  exit 1
+fi
 
-cp -r demo/ tmp/demo
-cp lib/*.js tmp/demo
-cp lib/stylesheets/*.css tmp/demo
+build_and_serve() {
+  rm -rf tmp/demo
+  mkdir -p tmp/demo
+  cp -r demo/ tmp/demo
+  cp lib/*.js tmp/demo
+  cp lib/stylesheets/*.css tmp/demo
 
-(
-  cd tmp/demo
-  open "http://localhost:$port"
-  ruby -run -e httpd . --port "$port"
-)
+  ruby -run -e httpd tmp/demo --port 3030
+}
+
+export -f build_and_serve
+
+find lib demo -type f | entr -s -r "build_and_serve"
